import { mcq } from "./helpers";

export const algorithmQuestions = [
  mcq(
    "ld-algo-02",
    "algorithms",
    "Algorithms",
    "hard",
    {
      language: "python",
      filename: "shortest_path.py",
      lines: [
        "def dijkstra(adj, source):",
        "    dist = {source: 0}",
        "    heap = [(0, source)]",
        "    while heap:",
        "        d, u = heappop(heap)",
        "        for v, w in adj[u]:  # w may be negative",
        "            if d + w < dist.get(v, inf):",
        "                dist[v] = d + w",
        "                heappush(heap, (dist[v], v))",
      ],
      highlightLines: [6, 7, 8],
    },
    "This shortest-path routine gives wrong results when edge weights are negative — standard fix?",
    [
      "Run Bellman-Ford or SPFA with negative-cycle detection instead of Dijkstra on the same graph",
      "Execute Dijkstra twice from different sources and combine distances to absorb negative edge effects",
      "Use BFS on an unweighted reduction of the graph and map results back to the original edge weights",
      "Flip the sign of all edge weights and run Dijkstra once, then negate distances at the end of the run",
    ],
    0,
    "Bellman-Ford handles negative edges with cycle check.",
    ["shortest path", "negative weights"],
  ),
  mcq(
    "ld-algo-03",
    "algorithms",
    "Algorithms",
    "medium",
    {
      language: "python",
      filename: "merge_logs.py",
      lines: [
        "def merge_k_sorted(streams):",
        "    heap = []",
        "    for i, it in enumerate(streams):",
        "        line = next(it, None)",
        "        if line is not None:",
        "            heappush(heap, (line, i, it))",
        "    while heap:",
        "        line, i, it = heappop(heap)",
        "        yield line",
        "        nxt = next(it, None)",
        "        if nxt is not None:",
        "            heappush(heap, (nxt, i, it))",
      ],
      highlightLines: [1, 2, 3, 4, 5],
    },
    "What property makes this pattern suitable for merging k large sorted log files with minimal memory?",
    [
      "Load every file into memory, concatenate, and run a single in-memory sort across all lines at once",
      "Perform a k-way merge with a min-heap holding the current head line from each open file stream",
      "Pairwise merge files in nested loops without preserving sorted order until one combined file remains",
      "Sample random lines from each file until all lines appear once, then sort the collected sample set",
    ],
    1,
    "Heap merge is O(total log k) time with O(k) memory.",
    ["k-way merge", "heap", "external sort"],
  ),
];
