import { mcq } from "./helpers";

export const algorithmQuestions = [
  mcq(
    "ld-algo-01",
    "algorithms",
    "Algorithms",
    "medium",
    "Streaming top-K frequent elements from a firehose with bounded memory. Which approach fits?",
    [
      "Spill the entire stream to disk each window and run a full sort to extract the top K keys exactly",
      "Use approximate heavy hitters such as count-min sketch or space-saving with stated error bounds",
      "Keep a hash map of every distinct key seen since process start and prune only when memory is full",
      "Maintain a sorted array of all keys seen so far and binary search each incoming event for rank",
    ],
    1,
    "Approximation trades exactness for bounded memory at scale.",
    ["streaming", "heavy hitters", "memory bounds"],
  ),
  mcq(
    "ld-algo-02",
    "algorithms",
    "Algorithms",
    "hard",
    "Dijkstra fails on graphs with negative edges. You need shortest paths with possible negative weights but no negative cycles. Standard fix?",
    [
      "Run Bellman-Ford or SPFA with negative-cycle detection instead of Dijkstra on the same graph",
      "Execute Dijkstra twice from different sources and combine distances to absorb negative edge effects",
      "Use BFS on an unweighted reduction of the graph and map results back to the original edge weights",
      "Flip the sign of all edge weights and run Dijkstra once, then negate distances at the end of the run",
    ],
    0,
    "Bellman-Ford handles negative edges with cycle check.",
    ["shortest path", "negative weights"],
  ),
  mcq(
    "ld-algo-03",
    "algorithms",
    "Algorithms",
    "medium",
    "Merge k sorted log files each with millions of lines using minimal memory. Best pattern?",
    [
      "Load every file into memory, concatenate, and run a single in-memory sort across all lines at once",
      "Perform a k-way merge with a min-heap holding the current head line from each open file stream",
      "Pairwise merge files in nested loops without preserving sorted order until one combined file remains",
      "Sample random lines from each file until all lines appear once, then sort the collected sample set",
    ],
    1,
    "Heap merge is O(total log k) time with O(k) memory.",
    ["k-way merge", "heap", "external sort"],
  ),
  mcq(
    "ld-algo-04",
    "algorithms",
    "Algorithms",
    "hard",
    "Cache with LRU eviction and TTL per key. Which design avoids O(n) scans on expiry?",
    [
      "Expire keys lazily on access plus periodic bucket cleanup or a timing wheel for due TTL batches",
      "Scan the full key set on every read to delete expired entries before returning a hit or miss result",
      "Disable per-key TTL and flush the entire cache on a single global interval to simplify eviction logic",
      "Store expiry timestamps only in a side map and walk all entries synchronously on each write operation",
    ],
    0,
    "Lazy + bucketed expiry amortizes cleanup cost.",
    ["LRU", "TTL", "cache design"],
  ),
];
