import { mcq } from "./helpers";

export const distributedQuestions = [
  mcq(
    "ld-dist-01",
    "distributed-systems",
    "Distributed Systems",
    "medium",
    {
      language: "yaml",
      filename: "service-a.config.yaml",
      lines: [
        "httpClient:",
        "  serviceB:",
        "    baseUrl: http://service-b",
        "    timeoutMs: 0",
        "    maxConnections: 500",
        "    retry:",
        "      attempts: 50",
        "      backoffMs: 0",
      ],
      highlightLines: [4, 5, 7, 8],
    },
    "Service A thread pools exhaust when Service B slows — what config strategy helps first?",
    [
      "Add client timeouts, bulkheads, and a circuit breaker with bounded retries or a defined fallback path",
      "Raise the maximum thread pool size without limits so slow calls queue instead of failing fast upstream",
      "Retry every failed call to B synchronously in a tight loop until B responds or the user disconnects",
      "Collapse A and B into one deployable unit so slow calls become in-process waits without network hops",
    ],
    0,
    "Timeouts + isolation prevent cascade; blind retries worsen overload.",
    ["circuit breaker", "bulkhead", "cascading failure"],
  ),
  mcq(
    "ld-dist-02",
    "distributed-systems",
    "Distributed Systems",
    "hard",
    {
      language: "yaml",
      filename: "kafka-consumer.yaml",
      lines: [
        "topic: orders",
        "partitions: 6",
        "consumers:",
        "  group: billing",
        "  instances: 2",
        "processing:",
        "  idempotent: true",
        "  orderingKey: orderId",
      ],
      highlightLines: [2, 5, 8],
    },
    "Consumer lag grows but order per orderId must be preserved — how do you scale safely?",
    [
      "Increase topic partitions and consumer group members up to partition count while keeping key routing",
      "Run a second consumer group on the same topic without coordination to double throughput per key",
      "Delete and recreate the topic with fewer partitions so each consumer processes more keys per poll",
      "Replace Kafka with a UDP fanout so consumers receive events faster without broker backpressure",
    ],
    0,
    "Parallelism bounded by partitions; key preserves order per entity.",
    ["Kafka", "partitioning", "ordering"],
  ),
];
