import { mcq } from "./helpers";

export const distributedQuestions = [
  mcq(
    "ld-dist-01",
    "distributed-systems",
    "Distributed Systems",
    "medium",
    "Microservice A calls B; B is slow; thread pools exhaust in A. Immediate resilience improvement?",
    [
      "Add client timeouts, bulkheads, and a circuit breaker with bounded retries or a defined fallback path",
      "Raise the maximum thread pool size without limits so slow calls queue instead of failing fast upstream",
      "Retry every failed call to B synchronously in a tight loop until B responds or the user disconnects",
      "Collapse A and B into one deployable unit so slow calls become in-process waits without network hops",
    ],
    0,
    "Timeouts + isolation prevent cascade; blind retries worsen overload.",
    ["circuit breaker", "bulkhead", "cascading failure"],
  ),
  mcq(
    "ld-dist-02",
    "distributed-systems",
    "Distributed Systems",
    "hard",
    "Kafka consumer lag grows; processing is idempotent but order matters per partition key. Scale consumers?",
    [
      "Increase topic partitions and consumer group members up to partition count while keeping key routing",
      "Run a second consumer group on the same topic without coordination to double throughput per key",
      "Delete and recreate the topic with fewer partitions so each consumer processes more keys per poll",
      "Replace Kafka with a UDP fanout so consumers receive events faster without broker backpressure",
    ],
    0,
    "Parallelism bounded by partitions; key preserves order per entity.",
    ["Kafka", "partitioning", "ordering"],
  ),
  mcq(
    "ld-dist-03",
    "distributed-systems",
    "Distributed Systems",
    "medium",
    "Split-brain in a leader-elected service during network partition. Prevention emphasis?",
    [
      "Require quorum majority for leadership grants and use fencing tokens before writers mutate shared state",
      "Allow two active leaders during partition if a load balancer distributes traffic evenly between them",
      "Rely on synchronized wall clocks across nodes to decide which leader is valid after partition heals",
      "Disable heartbeat timeouts temporarily so elected leaders never step down during brief network blips",
    ],
    0,
    "Quorum + fencing avoids dual writers.",
    ["leader election", "split brain", "quorum"],
  ),
  mcq(
    "ld-dist-04",
    "distributed-systems",
    "Distributed Systems",
    "hard",
    "Saga compensations fail mid-flow after partial success. Operational requirement?",
    [
      "Document manual runbooks only and require operators to fix stuck flows without persisted saga state",
      "Persist saga state, make compensations idempotent, and alert on stuck steps with safe replay tooling",
      "Enforce two-phase commit across every participating microservice for all long-running business flows",
      "Design sagas so compensations never fail by skipping rollback when any downstream call errors",
    ],
    1,
    "Durable orchestration state and idempotent compensations enable recovery.",
    ["saga", "compensation", "orchestration"],
  ),
];
