import { mcq } from "./helpers";

export const djangoQuestions = [
  mcq(
    "ld-django-01",
    "django",
    "Python / Django",
    "medium",
    "An ORM query in a loop causes 200 queries on a list page. The queryset already uses select_related for FK. What is the next likely fix?",
    [
      "Switch to raw SQL only",
      "Add prefetch_related for reverse M2M or reverse FK collections accessed in the loop",
      "Disable DEBUG",
      "Cache the entire Python process",
    ],
    1,
    "select_related covers FK joins; reverse relations need prefetch_related.",
    ["N+1", "prefetch_related", "ORM"],
  ),
  mcq(
    "ld-django-02",
    "django",
    "Python / Django",
    "hard",
    "Two Celery tasks update the same row using read-modify-write without locking. Sporadic lost updates appear under load. Safest Django-level approach?",
    [
      "Use select_for_update inside transaction.atomic around the critical section",
      "Increase Celery concurrency to finish faster",
      "Store counters only in Redis without DB",
      "Set ATOMIC_REQUESTS False globally",
    ],
    0,
    "Row-level lock in atomic block serializes conflicting updates.",
    ["concurrency", "transactions", "select_for_update"],
  ),
  mcq(
    "ld-django-03",
    "django",
    "Python / Django",
    "medium",
    "A view returns 403 for POST but GET works. CSRF middleware enabled, session cookie present. Mobile client uses JWT header API. Most plausible cause?",
    [
      "JWT replaces CSRF for session-authenticated browser forms; API client must use CSRF token or exempt endpoint intentionally",
      "GET always bypasses auth",
      "Django blocks POST on Sundays",
      "Middleware order irrelevant",
    ],
    0,
    "Session-backed POST expects CSRF; token auth paths differ from browser forms.",
    ["CSRF", "auth", "API vs browser"],
  ),
  mcq(
    "ld-django-04",
    "django",
    "Python / Django",
    "hard",
    "Migration adds non-null column to 50M-row table. Deploy window is short. Lowest-risk sequence?",
    [
      "Add nullable column, backfill in batches, then enforce NOT NULL with separate migration",
      "Add non-null with default in one step during peak traffic",
      "Drop table and recreate",
      "Use RunPython to lock table for hours",
    ],
    0,
    "Expand-backfill-contract avoids long locks and table rewrites where possible.",
    ["migrations", "zero-downtime", "backfill"],
  ),
  mcq(
    "ld-django-05",
    "django",
    "Python / Django",
    "medium",
    "Signals fire on every save and trigger external HTTP calls, slowing writes. Preferred refactor?",
    [
      "Disable signals globally",
      "Move side effects to explicit service layer or async task queued after commit",
      "Put HTTP in __init__",
      "Use sync requests in middleware",
    ],
    1,
    "Explicit domain services or on_commit tasks make side effects visible and testable.",
    ["signals", "on_commit", "side effects"],
  ),
];
