import { mcq } from "./helpers";

export const djangoQuestions = [
  mcq(
    "ld-django-01",
    "django",
    "Python / Django",
    "medium",
    "An ORM query in a loop causes 200 queries on a list page. The queryset already uses select_related for FK. What is the next likely fix?",
    [
      "Enable queryset caching on the view so repeated loop access hits the in-process ORM result cache only",
      "Add prefetch_related for reverse M2M or reverse FK collections that the loop touches on each row",
      "Rewrite the loop as one raw SQL statement with explicit joins for every relation accessed per iteration",
      "Raise the database connection pool limit so parallel per-row queries complete without queueing delay",
    ],
    1,
    "select_related covers FK joins; reverse relations need prefetch_related.",
    ["N+1", "prefetch_related", "ORM"],
  ),
  mcq(
    "ld-django-02",
    "django",
    "Python / Django",
    "hard",
    "Two Celery tasks update the same row using read-modify-write without locking. Sporadic lost updates appear under load. Safest Django-level approach?",
    [
      "Use select_for_update inside transaction.atomic around the read-modify-write critical section",
      "Run each task with autocommit enabled so commits finish faster and reduce overlap window on the row",
      "Mirror counters in Redis with GET and SET and stop reading the authoritative row during updates",
      "Pin that queue to a single Celery worker process so tasks never execute the critical section concurrently",
    ],
    0,
    "Row-level lock in atomic block serializes conflicting updates.",
    ["concurrency", "transactions", "select_for_update"],
  ),
  mcq(
    "ld-django-03",
    "django",
    "Python / Django",
    "medium",
    "A view returns 403 for POST but GET works. CSRF middleware enabled, session cookie present. Mobile client uses JWT header API. Most plausible cause?",
    [
      "Session POST expects CSRF; the client needs a CSRF token, an exempt route, or aligned session auth policy",
      "The mobile app must send the session cookie on POST exactly as on GET so authentication matches both verbs",
      "Register JWT before session auth globally so any Authorization header automatically bypasses CSRF on POST",
      "Mark the view csrf_exempt whenever a bearer token is present and rely on JWT validation for mutating calls",
    ],
    0,
    "Session-backed POST expects CSRF; token auth paths differ from browser forms.",
    ["CSRF", "auth", "API vs browser"],
  ),
  mcq(
    "ld-django-04",
    "django",
    "Python / Django",
    "hard",
    "Migration adds non-null column to 50M-row table. Deploy window is short. Lowest-risk sequence?",
    [
      "Add a nullable column, backfill in batches, then enforce NOT NULL in a follow-up migration after deploy",
      "Add the non-null column with a server default in one migration during peak traffic to finish faster",
      "Recreate the table empty with the new schema and bulk copy rows during a single maintenance window",
      "Run a long RunPython migration that locks the table until every row is updated in one transaction",
    ],
    0,
    "Expand-backfill-contract avoids long locks and table rewrites where possible.",
    ["migrations", "zero-downtime", "backfill"],
  ),
  mcq(
    "ld-django-05",
    "django",
    "Python / Django",
    "medium",
    "Signals fire on every save and trigger external HTTP calls, slowing writes. Preferred refactor?",
    [
      "Unregister all signal receivers at startup and invoke the same HTTP calls from model save overrides",
      "Move side effects to an explicit service layer or enqueue async work with on_commit after the transaction",
      "Keep signals but run synchronous requests inside pre_save so failures roll back before the row persists",
      "Call the external API from middleware on every response so writes stay fast and side effects stay global",
    ],
    1,
    "Explicit domain services or on_commit tasks make side effects visible and testable.",
    ["signals", "on_commit", "side effects"],
  ),
];
