import { mcq } from "./helpers";

export const djangoQuestions = [
  mcq(
    "ld-django-01",
    "django",
    "Python / Django",
    "medium",
    {
      language: "python",
      filename: "views.py",
      lines: [
        "def order_list(request):",
        "    orders = Order.objects.select_related('customer').all()",
        "    rows = []",
        "    for order in orders:",
        "        tags = order.tags.all()  # M2M",
        "        rows.append({'order': order, 'tags': list(tags)})",
        "    return JsonResponse({'rows': rows})",
      ],
      highlightLines: [4, 5],
    },
    "This list view triggers hundreds of SQL queries — what is the next ORM fix after select_related?",
    [
      "Enable queryset caching on the view so repeated loop access hits the in-process ORM result cache only",
      "Add prefetch_related for reverse M2M or reverse FK collections that the loop touches on each row",
      "Rewrite the loop as one raw SQL statement with explicit joins for every relation accessed per iteration",
      "Raise the database connection pool limit so parallel per-row queries complete without queueing delay",
    ],
    1,
    "select_related covers FK joins; reverse relations need prefetch_related.",
    ["N+1", "prefetch_related", "ORM"],
  ),
  mcq(
    "ld-django-02",
    "django",
    "Python / Django",
    "hard",
    {
      language: "python",
      filename: "tasks.py",
      lines: [
        "@shared_task",
        "def bump_inventory(sku: str, delta: int):",
        "    row = Inventory.objects.get(sku=sku)",
        "    row.qty = row.qty + delta",
        "    row.save(update_fields=['qty'])",
      ],
      highlightLines: [3, 4, 5],
    },
    "Concurrent Celery tasks lose inventory updates — what is the safest Django-level fix?",
    [
      "Use select_for_update inside transaction.atomic around the read-modify-write critical section",
      "Run each task with autocommit enabled so commits finish faster and reduce overlap window on the row",
      "Mirror counters in Redis with GET and SET and stop reading the authoritative row during updates",
      "Pin that queue to a single Celery worker process so tasks never execute the critical section concurrently",
    ],
    0,
    "Row-level lock in atomic block serializes conflicting updates.",
    ["concurrency", "transactions", "select_for_update"],
  ),
  mcq(
    "ld-django-03",
    "django",
    "Python / Django",
    "medium",
    {
      language: "python",
      filename: "views.py",
      lines: [
        "@api_view(['GET', 'POST'])",
        "def profile(request):",
        "    if request.method == 'GET':",
        "        return Response(serializer.data)",
        "    # POST from mobile app: Authorization: Bearer <jwt>",
        "    return Response(update_profile(request.data))",
      ],
      highlightLines: [6, 7],
    },
    "GET succeeds but session-authenticated POST returns 403 with CSRF middleware enabled — why?",
    [
      "Session POST expects CSRF; the client needs a CSRF token, an exempt route, or aligned session auth policy",
      "The mobile app must send the session cookie on POST exactly as on GET so authentication matches both verbs",
      "Register JWT before session auth globally so any Authorization header automatically bypasses CSRF on POST",
      "Mark the view csrf_exempt whenever a bearer token is present and rely on JWT validation for mutating calls",
    ],
    0,
    "Session-backed POST expects CSRF; token auth paths differ from browser forms.",
    ["CSRF", "auth", "API vs browser"],
  ),
];
