import { mcq } from "./helpers";

export const gisQuestions = [
  mcq(
    "ld-gis-02",
    "gis",
    "GIS",
    "hard",
    {
      language: "sql",
      filename: "nearby_drivers.sql",
      lines: [
        "SELECT driver_id",
        "FROM drivers",
        "WHERE ST_DWithin(",
        "  geom::geography,",
        "  ST_SetSRID(ST_MakePoint($lon, $lat), 4326)::geography,",
        "  5000",
        ");",
        "-- runs every second per vehicle; table has 2M rows, no spatial index",
      ],
      highlightLines: [3, 4, 5, 6, 9],
    },
    "This query must stay sub-second at scale — what database change helps most?",
    [
      "Use ST_DWithin on geography with a GiST index, simplify geometries, and partition hot spatial regions",
      "Scan the full points table each second and filter distances in SQL without spatial indexes on geometry",
      "Persist latitude and longitude as unparsed strings and parse them in the app layer for every comparison",
      "Compute haversine distance in application code over all rows loaded into memory on each vehicle tick",
    ],
    0,
    "Indexed geography predicates avoid brute force distance scans.",
    ["PostGIS", "indexing", "geospatial queries"],
  ),
  mcq(
    "ld-gis-03",
    "gis",
    "GIS",
    "medium",
    {
      language: "python",
      filename: "upload_geom.py",
      lines: [
        "def save_polygon(geojson: dict):",
        "    wkt = shape(geojson).wkt",
        "    with connection.cursor() as cur:",
        "        cur.execute(",
        "            'INSERT INTO zones (geom) VALUES (ST_GeomFromText(%s, 4326))',",
        "            [wkt],",
        "        )",
      ],
      highlightLines: [2, 4, 5, 6],
    },
    "Self-intersecting GeoJSON polygons break downstream spatial ops — server-side approach?",
    [
      "Accept all geometries and rely on the frontend map library to repair topology before users submit",
      "Validate topology with ST_IsValid, reject or repair under explicit policy, and log invalid submissions",
      "Convert GeoJSON to WKT on ingest without checks so downstream services normalize geometry later",
      "Skip server validation entirely and trust client-side checks to keep upload latency consistently low",
    ],
    1,
    "Invalid geometry breaks downstream spatial ops; validate server-side.",
    ["GeoJSON", "validation", "topology"],
  ),
];
