import { mcq } from "./helpers";

export const productionQuestions = [
  mcq(
    "ld-prod-02",
    "debugging",
    "Production / Debugging",
    "medium",
    {
      language: "javascript",
      filename: "validateEmail.js",
      lines: [
        "const EMAIL_RE =",
        "  /^([a-zA-Z0-9_\\.\\-\\+])+@([a-zA-Z0-9_\\-\\.])+\\.([a-zA-Z]{2,4})+$/;",
        "",
        "export function validateEmail(input) {",
        "  return EMAIL_RE.test(input);",
        "}",
      ],
      highlightLines: [1, 2, 5],
    },
    "CPU spikes on user input and profiles show catastrophic regex backtracking — priority fix?",
    [
      "Cap input size, use a safe regex or RE2-style engine, and add a regression test with pathological input",
      "Add CPU capacity to all API nodes so catastrophic backtracking completes before requests time out",
      "Disable request logging temporarily so regex work is the only CPU consumer visible in profiles",
      "Sample profiles less frequently so production overhead drops and average CPU metrics look healthier",
    ],
    0,
    "ReDoS is a code/input validation fix, not capacity only.",
    ["ReDoS", "profiling", "input validation"],
  ),
  mcq(
    "ld-prod-03",
    "production-devops",
    "Production / Debugging",
    "hard",
    {
      language: "typescript",
      filename: "apiClient.ts",
      lines: [
        "const API_URL = import.meta.env.VITE_API_URL;",
        "const STRIPE_SECRET = import.meta.env.VITE_STRIPE_SECRET_KEY;",
        "",
        "export async function charge(amount: number) {",
        "  return fetch(`${API_URL}/charge`, {",
        "    headers: { Authorization: `Bearer ${STRIPE_SECRET}` },",
        "    body: JSON.stringify({ amount }),",
        "  });",
        "}",
      ],
      highlightLines: [2, 6, 7],
    },
    "A scanner finds the Stripe secret in the client bundle — correct incident sequence?",
    [
      "Rotate the secret, remove it from client builds, audit access logs, and purge git history if needed",
      "Leave the secret in place because HTTPS encrypts the bundle in transit so exposure risk stays low",
      "Rename the environment variable in the repo without rotating credentials so scanners stop matching",
      "Publish a status page note with the old secret so users know to ignore it after the next deploy",
    ],
    0,
    "Rotation + removal from client + audit is standard incident hygiene.",
    ["secrets", "supply chain", "incident response"],
  ),
];
