import { mcq } from "./helpers";

export const reactQuestions = [
  mcq(
    "ld-react-01",
    "react-typescript",
    "React / TypeScript",
    "medium",
    "A list re-renders on every keystroke in a search box because parent state updates. Children are expensive pure components but still re-render. What is the most likely fix?",
    [
      "Move search state into each child so updates stay local",
      "Stabilize child props (memo + useCallback/useMemo for handlers and derived data passed down)",
      "Replace React with a virtual DOM library that batches less",
      "Force shouldComponentUpdate to always return false on children",
    ],
    1,
    "Unstable prop references defeat memo. Localizing state in every child breaks single source of truth for search.",
    ["render optimization", "memoization", "state colocation"],
  ),
  mcq(
    "ld-react-02",
    "react-typescript",
    "React / TypeScript",
    "hard",
    "StrictMode double-invokes effects in development. A fetch-on-mount effect creates duplicate subscriptions in prod after a bad merge. Best prevention?",
    [
      "Disable StrictMode in production builds only",
      "Use an abort controller / cleanup that cancels in-flight work and guard idempotent setup",
      "Move fetch to global window.onload",
      "Replace useEffect with useLayoutEffect to run once",
    ],
    1,
    "Correct pattern is abortable effects with cleanup; StrictMode exposes missing cleanup, not the root cause.",
    ["effects", "StrictMode", "resource cleanup"],
  ),
  mcq(
    "ld-react-03",
    "react-typescript",
    "React / TypeScript",
    "medium",
    "TypeScript narrows a discriminated union in a switch, but a shared handler widens the type back to the union. What typing approach keeps exhaustiveness?",
    [
      "Cast to any inside the handler",
      "Use a generic handler typed per case or separate functions per variant",
      "Disable strictNullChecks for that file",
      "Use enum instead of union",
    ],
    1,
    "Per-variant handlers or generics preserve narrowing; casts erase safety.",
    ["discriminated unions", "type narrowing"],
  ),
  mcq(
    "ld-react-04",
    "react-typescript",
    "React / TypeScript",
    "hard",
    "Concurrent features: a transition updates a large table while typing in a filter. Users see stale filter results briefly. Expected trade-off and mitigation?",
    [
      "Turn off concurrent rendering entirely",
      "Mark filter updates as urgent and defer table work with startTransition + deferred value",
      "Debounce keyboard to once per minute",
      "Move table to canvas",
    ],
    1,
    "Urgent user input vs deferred expensive render is the intended concurrent pattern.",
    ["concurrent React", "startTransition", "UX latency"],
  ),
  mcq(
    "ld-react-05",
    "react-typescript",
    "React / TypeScript",
    "medium",
    "A form library stores field state in refs to avoid re-renders, but error messages never update. What is the underlying issue?",
    [
      "Refs cannot hold strings",
      "UI derived from refs must trigger a render path (state or external store subscription)",
      "TypeScript blocks ref updates",
      "Errors must use class components",
    ],
    1,
    "Refs mutate without scheduling render; validated patterns expose observable field state.",
    ["controlled vs uncontrolled", "render scheduling"],
  ),
];
