import { mcq } from "./helpers";

export const reactQuestions = [
  mcq(
    "ld-react-01",
    "react-typescript",
    "React / TypeScript",
    "medium",
    "A list re-renders on every keystroke in a search box because parent state updates. Children are expensive pure components but still re-render. What is the most likely fix?",
    [
      "Colocate search state in each row so the parent tree skips updates when only one field changes locally",
      "Stabilize child props with memo plus useCallback and useMemo for handlers and derived data passed down",
      "Throttle parent setState while still passing fresh inline handlers and object literals to memoized children",
      "Wrap the list in extra context providers so keystrokes invalidate only the nearest subtree by design",
    ],
    1,
    "Unstable prop references defeat memo. Localizing state in every child breaks single source of truth for search.",
    ["render optimization", "memoization", "state colocation"],
  ),
  mcq(
    "ld-react-02",
    "react-typescript",
    "React / TypeScript",
    "hard",
    "StrictMode double-invokes effects in development. A fetch-on-mount effect creates duplicate subscriptions in prod after a bad merge. Best prevention?",
    [
      "Gate the fetch with a module flag so the second StrictMode invocation returns before subscribing in dev",
      "Use AbortController cleanup to cancel in-flight work and make subscription setup idempotent on remount",
      "Move the fetch to useLayoutEffect so the network call runs once before paint and skips strict checks",
      "Store the subscription handle in a ref and skip re-fetch when ref.current is already set after mount",
    ],
    1,
    "Correct pattern is abortable effects with cleanup; StrictMode exposes missing cleanup, not the root cause.",
    ["effects", "StrictMode", "resource cleanup"],
  ),
  mcq(
    "ld-react-03",
    "react-typescript",
    "React / TypeScript",
    "medium",
    "TypeScript narrows a discriminated union in a switch, but a shared handler widens the type back to the union. What typing approach keeps exhaustiveness?",
    [
      "Use one handler typed as the full union and rely on runtime typeof checks instead of compile-time cases",
      "Use a generic handler per case or separate functions per variant so narrowing survives the call boundary",
      "Replace the union with a numeric enum so the switch no longer needs exhaustiveness checking on variants",
      "Assert the discriminant with non-null bang inside the shared handler after the switch default branch",
    ],
    1,
    "Per-variant handlers or generics preserve narrowing; casts erase safety.",
    ["discriminated unions", "type narrowing"],
  ),
  mcq(
    "ld-react-04",
    "react-typescript",
    "React / TypeScript",
    "hard",
    "Concurrent features: a transition updates a large table while typing in a filter. Users see stale filter results briefly. Expected trade-off and mitigation?",
    [
      "Run table and filter updates synchronously in one setState batch so both always reflect the same snapshot",
      "Mark filter input urgent and defer heavy table work with startTransition and a deferred derived value",
      "Memoize the entire table with useMemo keyed on filter text so typing never schedules reconciliation work",
      "Offload filtering to a worker and postMessage on every keypress without prioritizing the input update path",
    ],
    1,
    "Urgent user input vs deferred expensive render is the intended concurrent pattern.",
    ["concurrent React", "startTransition", "UX latency"],
  ),
  mcq(
    "ld-react-05",
    "react-typescript",
    "React / TypeScript",
    "medium",
    "A form library stores field state in refs to avoid re-renders, but error messages never update. What is the underlying issue?",
    [
      "Read ref.current during render and feed it into useMemo so derived UI recalculates when refs mutate silently",
      "UI that depends on refs must go through state or a store subscription so mutations schedule a render pass",
      "Call flushSync after each ref write so validation errors paint immediately without lifting values to state",
      "Persist field errors in sessionStorage and poll on an interval instead of coupling errors to React updates",
    ],
    1,
    "Refs mutate without scheduling render; validated patterns expose observable field state.",
    ["controlled vs uncontrolled", "render scheduling"],
  ),
];
