import { mcq } from "./helpers";

export const reactQuestions = [
  mcq(
    "ld-react-01",
    "react-typescript",
    "React / TypeScript",
    "medium",
    {
      language: "tsx",
      filename: "ProductList.tsx",
      lines: [
        "function ProductList({ products }: { products: Product[] }) {",
        "  const [query, setQuery] = useState('');",
        "  return (",
        "    <>",
        "      <SearchBox value={query} onChange={setQuery} />",
        "      {products.map((p) => (",
        "        <MemoRow key={p.id} product={p} filter={query} onSelect={() => log(p.id)} />",
        "      ))}",
        "    </>",
        "  );",
        "}",
      ],
      highlightLines: [7, 8],
    },
    "Why do memoized MemoRow children re-render on every search keystroke?",
    [
      "Colocate search state in each row so parent updates skip when only one field changes locally",
      "Stabilize props with memo plus useCallback and useMemo for handlers and derived values passed down",
      "Throttle parent setState while passing fresh inline handlers and object literals to memoized children",
      "Wrap the list in extra context providers so keystrokes invalidate only the nearest subtree by design",
    ],
    1,
    "Unstable prop references defeat memo. Localizing state in every child breaks single source of truth for search.",
    ["render optimization", "memoization", "state colocation"],
  ),
  mcq(
    "ld-react-02",
    "react-typescript",
    "React / TypeScript",
    "hard",
    {
      language: "tsx",
      filename: "LiveFeed.tsx",
      lines: [
        "useEffect(() => {",
        "  const socket = connectFeed(roomId);",
        "  socket.on('message', (msg) => setMessages((m) => [...m, msg]));",
        "  return () => {",
        "    socket.off('message');",
        "    socket.disconnect();",
        "  };",
        "}, [roomId]);",
      ],
      highlightLines: [1, 2, 3],
    },
    "After StrictMode in dev, production shows duplicate websocket subscriptions — what is missing?",
    [
      "Gate the fetch with a module flag so the second StrictMode invocation returns before subscribing",
      "Use AbortController cleanup to cancel in-flight work and make subscription setup idempotent on remount",
      "Move the subscription to useLayoutEffect so the network call runs once before paint in strict checks",
      "Store the subscription handle in a ref and skip re-connect when ref.current is already set after mount",
    ],
    1,
    "Correct pattern is abortable effects with cleanup; StrictMode exposes missing cleanup, not the root cause.",
    ["effects", "StrictMode", "resource cleanup"],
  ),
  mcq(
    "ld-react-03",
    "react-typescript",
    "React / TypeScript",
    "medium",
    {
      language: "tsx",
      filename: "dispatchAction.ts",
      lines: [
        "type Action = { type: 'add'; item: Item } | { type: 'remove'; id: string };",
        "",
        "function handle(action: Action) {",
        "  switch (action.type) {",
        "    case 'add': return addItem(action.item);",
        "    case 'remove': return removeItem(action.id);",
        "    default: return assertNever(action);",
        "  }",
        "}",
      ],
      highlightLines: [3, 4, 5, 6, 7],
    },
    "TypeScript reports action.item may be undefined inside handle — how do you preserve exhaustiveness?",
    [
      "Use one handler typed as the full union and rely on runtime typeof checks instead of compile-time cases",
      "Use a generic handler per case or separate functions per variant so narrowing survives the call boundary",
      "Replace the union with a numeric enum so the switch no longer needs exhaustiveness checking on variants",
      "Assert the discriminant with non-null bang inside the shared handler after the switch default branch",
    ],
    1,
    "Per-variant handlers or generics preserve narrowing; casts erase safety.",
    ["discriminated unions", "type narrowing"],
  ),
];
