import { mcq } from "./helpers";

export const seniorQuestions = [
  mcq(
    "ld-senior-01",
    "senior-communication",
    "Senior Engineering / Communication",
    "medium",
    {
      language: "markdown",
      filename: "ADR-012-rewrite.md",
      lines: [
        "# ADR: Replace monolith with greenfield rewrite",
        "",
        "Status: Proposed",
        "Context: Revenue bugs in billing; stable catalog features",
        "Decision: Stop feature work 6 months; rewrite all services",
        "Consequences: Single cutover; no parallel run planned",
      ],
      highlightLines: [5, 6, 7],
    },
    "This rewrite ADR ignores ongoing revenue risk — what stance do you take in architecture review?",
    [
      "Advocate an incremental strangler with measurable SLO targets, rollback paths, and documented big-bang risk",
      "Approve an immediate full rewrite timeline so the team can fix structural issues in one coordinated push",
      "Block all structural change until revenue-critical bugs are zero, including incremental extraction work",
      "Defer the architecture decision to the most junior engineer present so the team practices ownership",
    ],
    0,
    "Senior communication balances risk, business continuity, and measurable migration.",
    ["architecture review", "rewrite vs evolve", "stakeholders"],
  ),
  mcq(
    "ld-senior-02",
    "senior-communication",
    "Senior Engineering / Communication",
    "hard",
    {
      language: "markdown",
      filename: "postmortem-draft.md",
      lines: [
        "# Incident: checkout outage",
        "",
        "Root cause: On-call engineer deployed wrong config.",
        "Action items:",
        "- Fire on-call for negligence",
        "- No process changes needed",
      ],
      highlightLines: [4, 6, 7],
    },
    "The postmortem draft blames the on-call engineer — best facilitation move?",
    [
      "Steer the review toward timeline, contributing factors, and actionable follow-ups separate from people",
      "Call out responsible individuals in the meeting so accountability is clear before publishing the doc",
      "Cancel the postmortem when tone turns blameful and revisit only after leadership selects a scapegoat",
      "Publish raw chat transcripts externally so the community can judge who caused the outage fairly",
    ],
    0,
    "Blameless postmortems improve learning and reduce fear of reporting.",
    ["incident review", "blameless culture"],
  ),
  mcq(
    "ld-senior-03",
    "senior-communication",
    "Senior Engineering / Communication",
    "medium",
    {
      language: "markdown",
      filename: "roadmap-slack.md",
      lines: [
        "Product: Can we ship the payments migration by March 15?",
        "",
        "Engineering reply draft:",
        "- Yes, March 15 is guaranteed",
        "- Depends on 3 teams we have not scoped yet",
        "- Unknown: legacy PCI audit window",
      ],
      highlightLines: [4, 5, 6],
    },
    "Product needs a date for a multi-team dependency with high uncertainty — how do you respond?",
    [
      "Commit a fixed ship date to unblock sales even though engineering confidence in the estimate is low",
      "Offer a date range with stated assumptions, milestones, unknowns, and a spike to reduce uncertainty",
      "Decline to discuss dates until every unknown is resolved so product cannot plan downstream work",
      "Stop attending product planning sessions until stakeholders accept that engineering cannot estimate",
    ],
    1,
    "Transparent ranges and discovery work are senior-level expectation setting.",
    ["estimation", "cross-team communication", "risk"],
  ),
];
