import { mcq } from "./helpers";

export const sqlQuestions = [
  mcq(
    "ld-sql-01",
    "sql-postgresql",
    "SQL / PostgreSQL",
    "medium",
    "EXPLAIN shows seq scan on a filtered column with 2% selectivity; index exists but planner ignores it. Statistics are stale after bulk load. First action?",
    [
      "Rebuild the index concurrently so the planner treats it as fresh without touching table statistics",
      "Run ANALYZE on the table and revisit whether the planner cost estimates match current data distribution",
      "Set enable_seqscan off globally so every query on that table must use the existing btree index path",
      "Raise shared_buffers and work_mem together so sequential scans become cheaper than index lookups",
    ],
    1,
    "Stale stats mislead cost estimates; ANALYZE refreshes distribution info.",
    ["query planner", "ANALYZE", "indexes"],
  ),
  mcq(
    "ld-sql-02",
    "sql-postgresql",
    "SQL / PostgreSQL",
    "hard",
    "Serializable transaction reports serialization failure under concurrent bookings. Business rule: no double-book same slot. Best handling?",
    [
      "Retry the transaction with bounded backoff when serialization failure occurs and keep transactions short",
      "Lower isolation to read committed and rely on application checks alone without database conflict detection",
      "Remove the unique or exclusion constraints so concurrent writers never surface serialization failures",
      "Take an exclusive lock on the entire bookings table for every insert to serialize all writers globally",
    ],
    0,
    "Serializable + retry is valid; also consider explicit exclusion constraints and shorter transactions.",
    ["isolation levels", "retries", "booking"],
  ),
  mcq(
    "ld-sql-03",
    "sql-postgresql",
    "SQL / PostgreSQL",
    "medium",
    "A pagination query uses OFFSET 500000 and becomes slow. Keyset pagination is possible on created_at,id. Why is keyset better here?",
    [
      "OFFSET still reads every skipped row but avoids sorting when the table has a primary key on id alone",
      "Keyset seeks from the last seen tuple using the index instead of scanning and discarding offset rows",
      "Keyset pagination forces a sequential scan because the cursor column cannot use a composite index",
      "OFFSET is slower only when autovacuum is behind; keyset fixes planner statistics rather than scan cost",
    ],
    1,
    "Large OFFSET forces scanning discarded rows; keyset uses index seek.",
    ["pagination", "keyset", "performance"],
  ),
  mcq(
    "ld-sql-04",
    "sql-postgresql",
    "SQL / PostgreSQL",
    "hard",
    "Long-running migration holds AccessExclusiveLock; app timeouts spike. Operational mitigation during deploy?",
    [
      "Set lock_timeout and statement_timeout and split the migration into shorter phases with safe rollback",
      "Disable synchronous_commit cluster-wide permanently so DDL locks release faster during heavy traffic",
      "Run the migration from an ad hoc client session without timeouts so it always completes in one pass",
      "Terminate all application connections preemptively on every deploy so migrations never wait on clients",
    ],
    0,
    "Phased migrations and lock timeouts bound blast radius.",
    ["locks", "migrations", "operations"],
  ),
];
