import { mcq } from "./helpers";

export const systemDesignQuestions = [
  mcq(
    "ld-sd-02",
    "system-design",
    "System Design",
    "hard",
    {
      language: "typescript",
      filename: "webhookHandler.ts",
      lines: [
        "app.post('/webhooks/payment', async (req, res) => {",
        "  const key = req.headers['idempotency-key'] as string;",
        "  const payload = req.body;",
        "  await ledger.credit(payload.accountId, payload.amount);",
        "  res.status(200).send('ok');",
        "});",
      ],
      highlightLines: [2, 4, 5],
    },
    "Duplicate webhook deliveries can double-credit accounts — how do you guarantee exactly-once effect?",
    [
      "Return HTTP 200 on duplicate delivery without recording anything so the provider stops retrying quickly",
      "Store the idempotency key with the processed outcome in durable storage inside the same transaction",
      "Switch the webhook endpoint to GET with the payment id in query params so retries are naturally safe",
      "Keep the last seen client UUID in process memory and reject duplicates until the pod restarts",
    ],
    1,
    "Durable idempotency record makes retries safe.",
    ["idempotency", "webhooks", "payments"],
  ),
  mcq(
    "ld-sd-03",
    "system-design",
    "System Design",
    "medium",
    {
      language: "typescript",
      filename: "uploadRoute.ts",
      lines: [
        "app.post('/upload', upload.single('file'), async (req, res) => {",
        "  const buffer = req.file.buffer;  // entire 5GB file",
        "  const key = `uploads/${req.user.id}/${req.file.originalname}`;",
        "  await s3.putObject({ Bucket, Key: key, Body: buffer });",
        "  res.json({ key });",
        "});",
      ],
      highlightLines: [2, 4],
    },
    "API pods OOM on 5GB uploads — what architecture change fixes this handler?",
    [
      "Stream uploads to object storage via signed multipart upload while the API orchestrates parts only",
      "Vertically scale API pod memory so each instance can buffer a full 5GB object during the request",
      "Accept base64-encoded file bodies in JSON so clients chunk logically without changing server design",
      "Store upload bytes in signed session cookies and assemble the object on the final chunk request",
    ],
    0,
    "Direct-to-storage multipart avoids loading blob in app memory.",
    ["object storage", "multipart upload", "streaming"],
  ),
  mcq(
    "ld-sd-05",
    "system-design",
    "System Design",
    "medium",
    {
      language: "yaml",
      filename: "flags.yaml",
      lines: [
        "flags:",
        "  checkout_v2:",
        "    default: true",
        "    rollout: 100",
        "  risky_search:",
        "    default: false",
        "    rollout: 0",
        "# deployed via git push; prod still serves old bundle until next release",
      ],
      highlightLines: [7, 8],
    },
    "Flags must flip worldwide within seconds without redeploy — minimal viable design?",
    [
      "Rebuild and redeploy the frontend on a fixed hourly schedule so flag defaults propagate predictably",
      "Run a versioned config service with poll or push subscriptions and a short client-side cache TTL",
      "Commit flag values to git and rely on the next routine release train to pick up changes globally",
      "Email updated flag payloads to power users and ask them to refresh the browser to pick up changes",
    ],
    1,
    "Versioned remote config with TTL/subscription enables fast rollout control.",
    ["feature flags", "configuration", "rollout"],
  ),
];
