import { mcq } from "./helpers";

export const systemDesignQuestions = [
  mcq(
    "ld-sd-01",
    "system-design",
    "System Design",
    "medium",
    "Read-heavy product catalog; writes are rare. P99 read latency spikes when marketing runs a flash sale (reads only). First scaling lever?",
    [
      "Add read replicas and cache hot catalog keys with explicit invalidation when product data changes",
      "Shard the write path first so each catalog partition serves reads locally without a shared cache tier",
      "Serve the full catalog from browser localStorage on each client and skip server reads during the sale",
      "Throttle marketing traffic at the CDN edge only while keeping origin reads uncached for freshness",
    ],
    0,
    "Read path scales with replicas/cache; flash traffic is read amplification.",
    ["caching", "read replicas", "invalidation"],
  ),
  mcq(
    "ld-sd-02",
    "system-design",
    "System Design",
    "hard",
    "Idempotent payment webhook may arrive twice. How do you guarantee exactly-once business effect?",
    [
      "Return HTTP 200 on duplicate delivery without recording anything so the provider stops retrying quickly",
      "Store the idempotency key with the processed outcome in durable storage inside the same transaction",
      "Switch the webhook endpoint to GET with the payment id in query params so retries are naturally safe",
      "Keep the last seen client UUID in process memory and reject duplicates until the pod restarts",
    ],
    1,
    "Durable idempotency record makes retries safe.",
    ["idempotency", "webhooks", "payments"],
  ),
  mcq(
    "ld-sd-03",
    "system-design",
    "System Design",
    "medium",
    "Upload service accepts 5GB files. API servers run out of memory. Architecture change?",
    [
      "Stream uploads to object storage via signed multipart upload while the API orchestrates parts only",
      "Vertically scale API pod memory so each instance can buffer a full 5GB object during the request",
      "Accept base64-encoded file bodies in JSON so clients chunk logically without changing server design",
      "Store upload bytes in signed session cookies and assemble the object on the final chunk request",
    ],
    0,
    "Direct-to-storage multipart avoids loading blob in app memory.",
    ["object storage", "multipart upload", "streaming"],
  ),
  mcq(
    "ld-sd-04",
    "system-design",
    "System Design",
    "hard",
    "Global users need low-latency reads; writes must remain strongly consistent for financial balances. Realistic pattern?",
    [
      "Single write primary with regional read replicas and bounded staleness only for non-balance read paths",
      "Active-active writable replicas in every region without cross-region coordination on balance updates",
      "Merge balance reads client-side by taking the maximum value reported from two random region endpoints",
      "Use eventual consistency for balance rows and reconcile discrepancies in a nightly batch job only",
    ],
    0,
    "Strong consistency for money usually implies single writer path; selective staleness elsewhere.",
    ["CAP trade-offs", "financial consistency", "multi-region"],
  ),
  mcq(
    "ld-sd-05",
    "system-design",
    "System Design",
    "medium",
    "Feature flags must update within seconds worldwide without redeploy. Minimal viable design?",
    [
      "Rebuild and redeploy the frontend on a fixed hourly schedule so flag defaults propagate predictably",
      "Run a versioned config service with poll or push subscriptions and a short client-side cache TTL",
      "Commit flag values to git and rely on the next routine release train to pick up changes globally",
      "Email updated flag payloads to power users and ask them to refresh the browser to pick up changes",
    ],
    1,
    "Versioned remote config with TTL/subscription enables fast rollout control.",
    ["feature flags", "configuration", "rollout"],
  ),
];
