import { mcq } from "./helpers";

export const systemDesignQuestions = [
  mcq(
    "ld-sd-01",
    "system-design",
    "System Design",
    "medium",
    "Read-heavy product catalog; writes are rare. P99 read latency spikes when marketing runs a flash sale (reads only). First scaling lever?",
    [
      "Add read replicas + cache hot keys with explicit invalidation on write",
      "Shard writes before reads",
      "Move catalog to client localStorage only",
      "Disable marketing",
    ],
    0,
    "Read path scales with replicas/cache; flash traffic is read amplification.",
    ["caching", "read replicas", "invalidation"],
  ),
  mcq(
    "ld-sd-02",
    "system-design",
    "System Design",
    "hard",
    "Idempotent payment webhook may arrive twice. How do you guarantee exactly-once business effect?",
    [
      "Ignore second HTTP call silently without storage",
      "Store idempotency key with processed outcome in durable store inside transaction",
      "Use GET for webhook",
      "Rely on client UUID in memory",
    ],
    1,
    "Durable idempotency record makes retries safe.",
    ["idempotency", "webhooks", "payments"],
  ),
  mcq(
    "ld-sd-03",
    "system-design",
    "System Design",
    "medium",
    "Upload service accepts 5GB files. API servers run out of memory. Architecture change?",
    [
      "Stream to object storage with signed multipart upload; API orchestrates, not buffers whole file",
      "Increase RAM on API pods only",
      "Base64 in JSON body",
      "Store files in session cookie",
    ],
    0,
    "Direct-to-storage multipart avoids loading blob in app memory.",
    ["object storage", "multipart upload", "streaming"],
  ),
  mcq(
    "ld-sd-04",
    "system-design",
    "System Design",
    "hard",
    "Global users need low-latency reads; writes must remain strongly consistent for financial balances. Realistic pattern?",
    [
      "Single primary region for writes with read replicas elsewhere accepting bounded staleness for non-balance reads",
      "Active-active writable everywhere without coordination",
      "Client-side random balance merge",
      "Eventual consistency for balances",
    ],
    0,
    "Strong consistency for money usually implies single writer path; selective staleness elsewhere.",
    ["CAP trade-offs", "financial consistency", "multi-region"],
  ),
  mcq(
    "ld-sd-05",
    "system-design",
    "System Design",
    "medium",
    "Feature flags must update within seconds worldwide without redeploy. Minimal viable design?",
    [
      "Rebuild frontend hourly",
      "Config service polled/subscribed with versioned flag payload and client cache TTL",
      "Hardcode flags in git",
      "Email flags to users",
    ],
    1,
    "Versioned remote config with TTL/subscription enables fast rollout control.",
    ["feature flags", "configuration", "rollout"],
  ),
];
